apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loadbalancer
  labels:
    app: loadbalancer
    version: v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: loadbalancer
        version: v1
    spec:
      volumes:
        - name: ssl-cert
          secret:
            secretName: ssl-certs
      containers:
      - image: thehumaneffort/kube-haproxy-lb:0.4
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - name: ssl-cert
            mountPath: /dev/ssl-cert
            readOnly: true
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
          - containerPort: 80
            hostPort: 80
            protocol: TCP
          - containerPort: 443
            hostPort: 443
            protocol: TCP
        args:
          - --ssl-cert=/dev/ssl-cert/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loadbalancer
    version: v1
  name: loadbalancer
spec:
  ports:
  - name: port-2
    port: 443
    protocol: TCP
    targetPort: 443
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: loadbalancer
    version: v1
  type: LoadBalancer
