apiVersion: v1
kind: ReplicationController
metadata:
  name: service-loadbalancer
  labels:
    app: service-loadbalancer
    version: v1
spec:
  replicas: 1
  selector:
    app: service-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: service-loadbalancer
        version: v1
    spec:
      nodeSelector:
        role: loadbalancer
      volumes:
        - name: ssl-cert
          secret:
            secretName: ssl-certs
      containers:
      - image: us.gcr.io/kubetest-1319/kube-haproxy-lb:0.4.2
        volumeMounts:
          - name: ssl-cert
            mountPath: /dev/ssl-cert
            readOnly: true
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        name: haproxy
        ports:
        # All http services
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        # nginx https
        - containerPort: 443
          hostPort: 8080
          protocol: TCP
        # mysql
        # - containerPort: 3306
        #   hostPort: 3306
        #   protocol: TCP
        # # haproxy stats
        # - containerPort: 1936
        #   hostPort: 1936
        #   protocol: TCP
        resources: {}
        args:
        - --ssl-cert=/dev/ssl-cert/
#        - --tcp-services=mysql:3306,nginxsvc:443
